export interface TypingData {
	id: string
	title: string
	data: string[][]
}

export const typingData: TypingData[] = [
	{
		id: '019ee625-b455-7c9f-9a17-a23a31310d05',
		title: 'Sensores MEMS na Manutenção Preditiva',
		data: [
			['MEMS sensors,', 'Os sensores MEMS,'],
			['especially accelerometers', 'especialmente acelerômetros'],
			['and inertial measurement units,', 'e unidades de medição inercial,'],
			['have transformed the way', 'têm transformado a forma como'],
			['industry monitors rotating equipment.', 'a indústria monitora equipamentos rotativos.'],
			['Installed in motors, pumps and gearboxes,', 'Instalados em motores, bombas e redutores,'],
			['these sensors capture', 'esses sensores capturam'],
			['vibration data in real time,', 'dados de vibração em tempo real,'],
			['allowing the identification of', 'permitindo identificar'],
			['abnormal patterns associated with', 'padrões anormais associados a'],
			['misalignments, imbalances,', 'desalinhamentos, desbalanceamentos,'],
			['bearing wear', 'desgaste de rolamentos'],
			['and other mechanical failures.', 'e outras falhas mecânicas.'],
			['Combined with IoT platforms', 'Combinados a plataformas IoT'],
			['and data analysis algorithms,', 'e algoritmos de análise de dados,'],
			['MEMS sensors enable', 'os sensores MEMS possibilitam'],
			['predictive maintenance,', 'a manutenção preditiva,'],
			['reducing unplanned downtime', 'reduzindo paradas não planejadas'],
			['and operational costs.', 'e custos operacionais.'],
			['Their compact size,', 'Seu tamanho compacto,'],
			['low power consumption', 'baixo consumo de energia'],
			['and affordable cost', 'e custo acessível'],
			['make this technology', 'tornam essa tecnologia'],
			['an increasingly adopted solution', 'uma solução cada vez mais adotada'],
			['in modern industry.', 'na indústria moderna.'],
		],
	},
	{
		id: '019ee625-ef84-79b5-a439-0ad6b911aa18',
		title: 'ESP32: Conectividade Inteligente para IoT',
		data: [
			['Embedded systems', 'Os sistemas embarcados'],
			['play a fundamental role', 'têm papel fundamental'],
			['in the development of', 'no desenvolvimento de'],
			['Internet of Things solutions,', 'soluções de Internet das Coisas,'],
			['with platforms like the ESP32 standing out.', 'destacando-se plataformas como o ESP32.'],
			['This microcontroller combines', 'Esse microcontrolador combina'],
			['low cost,', 'baixo custo,'],
			['low power consumption', 'baixo consumo de energia'],
			['and high processing capacity,', 'e alta capacidade de processamento,'],
			['while also offering', 'além de oferecer'],
			[
				'integrated WiFi and Bluetooth Low Energy connectivity.',
				'conectividade WiFi e Bluetooth Low Energy integradas.',
			],
			['WiFi enables direct communication', 'O WiFi permite comunicação direta'],
			['with servers,', 'com servidores,'],
			['cloud applications', 'aplicações em nuvem'],
			['and local networks,', 'e redes locais,'],
			['while BLE makes possible', 'enquanto o BLE possibilita'],
			['efficient connections', 'conexões eficientes'],
			['with smartphones, sensors', 'com smartphones, sensores'],
			['and low-power devices.', 'e dispositivos de baixo consumo energético.'],
			['This versatility makes the ESP32 ideal', 'Essa versatilidade torna o ESP32 ideal'],
			['for home automation,', 'para automação residencial,'],
			['industrial monitoring,', 'monitoramento industrial,'],
			['asset tracking', 'rastreamento de ativos'],
			['and smart projects in general,', 'e projetos inteligentes em geral,'],
			['accelerating the development', 'acelerando o desenvolvimento'],
			['of connected and scalable applications.', 'de aplicações conectadas e escaláveis.'],
		],
	},
	{
		id: '019ee665-fb5a-7dad-bf60-78a76574104b',
		title: 'Indústria 4.0 e a Transformação Digital',
		data: [
			['Industry 4.0 represents', 'A Indústria 4.0 representa'],
			['the integration of digital technologies', 'a integração de tecnologias digitais'],
			['into production processes,', 'aos processos produtivos,'],
			['making factories smarter,', 'tornando fábricas mais inteligentes,'],
			['more connected and efficient.', 'conectadas e eficientes.'],
			['In this scenario,', 'Nesse cenário,'],
			['IoT systems', 'os sistemas IoT'],
			['play a fundamental role', 'desempenham papel fundamental'],
			['in collecting real-time data', 'ao coletar dados em tempo real'],
			['from machines, sensors and equipment,', 'de máquinas, sensores e equipamentos,'],
			['enabling continuous monitoring', 'permitindo monitoramento contínuo'],
			['and decision-making', 'e tomada de decisões'],
			['based on accurate information.', 'baseada em informações precisas.'],
			['With the adoption of these technologies,', 'Com a adoção dessas tecnologias,'],
			[
				'industries are able to increase productivity,',
				'as indústrias conseguem aumentar a produtividade,',
			],
			['reduce waste,', 'reduzir desperdícios,'],
			['optimize energy consumption', 'otimizar o consumo de energia'],
			['and minimize unplanned downtime', 'e minimizar paradas não planejadas'],
			['through predictive maintenance.', 'por meio da manutenção preditiva.'],
			['In addition,', 'Além disso,'],
			['connectivity between systems', 'a conectividade entre sistemas'],
			['improves product quality', 'melhora a qualidade dos produtos'],
			['and competitiveness,', 'e a competitividade,'],
			['generating significant', 'gerando ganhos'],
			['operational and financial gains.', 'operacionais e financeiros significativos.'],
		],
	},
	{
		id: '019ee666-88a4-78f4-8fa6-78105ebe7bf5',
		title: 'BLE 5+: Mais Alcance e Velocidade com Energia Mínima',
		data: [
			['Bluetooth Low Energy technology', 'A tecnologia Bluetooth Low Energy'],
			['represents a milestone', 'representa um marco'],
			['in wireless communication', 'na comunicação sem fio'],
			['aimed at devices', 'voltada para dispositivos'],
			['that require energy efficiency.', 'que exigem eficiência energética.'],
			['With the arrival of version 5', 'Com a chegada da versão 5'],
			['and its later updates,', 'e suas atualizações posteriores,'],
			['BLE has evolved significantly:', 'o BLE evoluiu significativamente:'],
			['it doubled the transmission speed,', 'dobrou a velocidade de transmissão,'],
			['quadrupled the range', 'quadruplicou o alcance'],
			['and expanded the broadcast capacity,', 'e ampliou a capacidade de broadcast,'],
			['becoming ideal for IoT,', 'tornando-se ideal para IoT,'],
			['wearables and sensors.', 'vestíveis e sensores.'],
			['Its main differentiator', 'Seu principal diferencial'],
			['remains the extremely low', 'continua sendo o baixíssimo'],
			['power consumption,', 'consumo de energia,'],
			['allowing devices to operate', 'permitindo que dispositivos funcionem'],
			['for months or even years', 'por meses ou até anos'],
			['on a single coin cell battery.', 'com uma única bateria de moeda.'],
			['This combination', 'Essa combinação'],
			['of performance and economy', 'de desempenho e economia'],
			['established BLE as an essential standard', 'consolidou o BLE como padrão essencial'],
			['in modern connectivity.', 'na conectividade moderna.'],
		],
	},
	{
		id: '019ef1e1-4d1a-7570-8341-abc2d2fe8a00',
		title: 'Computação em Nuvem: O Motor da Era Digital',
		data: [
			['Cloud computing has transformed', 'A computação em nuvem transformou'],
			['the way companies and people', 'a maneira como empresas e pessoas'],
			['store data and run applications.', 'armazenam dados e executam aplicações.'],
			['Instead of relying on', 'Em vez de depender de'],
			['local physical servers,', 'servidores físicos locais,'],
			['the cloud offers on-demand resources', 'a nuvem oferece recursos sob demanda'],
			['over the internet,', 'pela internet,'],
			['ensuring scalability, flexibility', 'garantindo escalabilidade, flexibilidade'],
			['and cost reduction.', 'e redução de custos.'],
			['This approach allows organizations', 'Essa abordagem permite que organizações'],
			['to grow in an agile way,', 'cresçam de forma ágil,'],
			['paying only for what they use', 'pagando apenas pelo que utilizam'],
			['and without large investments', 'e sem grandes investimentos'],
			['in infrastructure.', 'em infraestrutura.'],
			['In addition,', 'Além disso,'],
			['the cloud enables innovations', 'a nuvem viabiliza inovações'],
			['in artificial intelligence, big data', 'em inteligência artificial, big data'],
			['and remote work,', 'e trabalho remoto,'],
			['sustaining much of', 'sustentando boa parte'],
			["today's digital transformation.", 'da transformação digital atual.'],
			['With high availability', 'Com alta disponibilidade'],
			['and enhanced security,', 'e segurança aprimorada,'],
			['it has become the backbone', 'ela se tornou a espinha dorsal'],
			['of modern businesses,', 'de negócios modernos,'],
			['driving agility and competitiveness', 'impulsionando agilidade e competitividade'],
			['in virtually every sector', 'em praticamente todos os setores'],
			['of the economy.', 'da economia.'],
		],
	},
	{
		id: '019ef1e5-3666-754c-83fb-59b736c2d304',
		title: 'Cibersegurança: Proteção na Era da Conectividade Total',
		data: [
			['In an increasingly connected world,', 'Em um mundo cada vez mais conectado,'],
			['cybersecurity has become', 'a cibersegurança tornou-se'],
			['an indispensable priority.', 'uma prioridade indispensável.'],
			['With the growing volume of data', 'Com o volume crescente de dados'],
			['traveling across the internet', 'trafegando pela internet'],
			['at every moment,', 'a cada instante,'],
			['the opportunities for attacks', 'as oportunidades para ataques'],
			['have grown in the same proportion.', 'cresceram na mesma proporção.'],
			['Protecting sensitive information', 'Proteger informações sensíveis'],
			['requires layers of defense,', 'exige camadas de defesa,'],
			['such as encryption,', 'como criptografia,'],
			['multi-factor authentication', 'autenticação multifator'],
			['and continuous threat monitoring.', 'e monitoramento contínuo de ameaças.'],
			['Companies and individuals', 'Empresas e indivíduos'],
			['need to adopt a proactive stance,', 'precisam adotar uma postura proativa,'],
			['updating systems', 'atualizando sistemas'],
			['and cultivating a culture', 'e cultivando uma cultura'],
			['of digital awareness.', 'de conscientização digital.'],
			['More than technology,', 'Mais do que tecnologia,'],
			['cybersecurity involves behavior', 'a cibersegurança envolve comportamento'],
			['and shared responsibility.', 'e responsabilidade compartilhada.'],
			['In times of total connectivity,', 'Em tempos de conectividade total,'],
			['ensuring the integrity', 'garantir a integridade'],
			['and privacy of data', 'e a privacidade dos dados'],
			['is no longer optional', 'deixou de ser opcional'],
			['and has become essential', 'e passou a ser essencial'],
			['for trust in the digital environment.', 'para a confiança no ambiente digital.'],
		],
	},
	{
		id: '019ef1e9-a9a0-7e90-a723-c506e4c42518',
		title: 'Economia dos Dados: O Novo Petróleo da Era Digital',
		data: [
			['Data has become', 'Os dados se tornaram'],
			['one of the most valuable assets', 'um dos ativos mais valiosos'],
			['of the 21st century,', 'do século XXI,'],
			['often compared to the oil', 'comparados frequentemente ao petróleo'],
			['that drove the industrial economy.', 'que movimentou a economia industrial.'],
			['With every digital interaction,', 'A cada interação digital,'],
			['we generate information that,', 'geramos informações que,'],
			['when collected and analyzed,', 'quando coletadas e analisadas,'],
			['reveals patterns of behavior,', 'revelam padrões de comportamento,'],
			['preferences and market trends.', 'preferências e tendências de mercado.'],
			['Companies that master the art', 'Empresas que dominam a arte'],
			['of turning data into insights', 'de transformar dados em insights'],
			['gain a competitive advantage,', 'ganham vantagem competitiva,'],
			['personalizing products', 'personalizando produtos'],
			['and anticipating demands.', 'e antecipando demandas.'],
			['However, just like oil,', 'No entanto, assim como o petróleo,'],
			['data needs to be refined:', 'os dados precisam ser refinados:'],
			['without proper analysis and governance,', 'sem análise e governança adequadas,'],
			['it loses value.', 'perdem valor.'],
			['This new economy', 'Essa nova economia'],
			['also raises debates', 'também levanta debates'],
			['about privacy and ethics', 'sobre privacidade e ética'],
			['in the use of information.', 'no uso das informações.'],
			['Mastering data, today,', 'Dominar os dados, hoje,'],
			['means leading the digital transformation.', 'significa liderar a transformação digital.'],
		],
	},
	{
		id: '019ef1ea-989d-7732-9752-11cfe77538ae',
		title: 'Marketing Orientado por Dados: Decisões Mais Inteligentes',
		data: [
			['Digital marketing has evolved', 'O marketing digital evoluiu'],
			['from campaigns based on intuition', 'de campanhas baseadas em intuição'],
			['to strategies guided by concrete data.', 'para estratégias guiadas por dados concretos.'],
			['Today, every click,', 'Hoje, cada clique,'],
			['view and interaction', 'visualização e interação'],
			['provides valuable information', 'fornece informações valiosas'],
			['about consumer behavior.', 'sobre o comportamento do consumidor.'],
			['By analyzing this data,', 'Ao analisar esses dados,'],
			['companies can segment audiences', 'as empresas conseguem segmentar públicos'],
			['with precision,', 'com precisão,'],
			['personalize messages', 'personalizar mensagens'],
			['and invest resources', 'e investir recursos'],
			['where they truly generate results.', 'onde realmente geram resultado.'],
			['Analytics and automation tools', 'Ferramentas de análise e automação'],
			['allow performance to be measured', 'permitem medir o desempenho'],
			['in real time,', 'em tempo real,'],
			['adjusting campaigns', 'ajustando campanhas'],
			['in an agile and efficient way.', 'de forma ágil e eficiente.'],
			['This approach reduces waste,', 'Essa abordagem reduz desperdícios,'],
			['increases return on investment', 'aumenta o retorno sobre investimento'],
			['and strengthens', 'e fortalece'],
			['the relationship with the customer.', 'o relacionamento com o cliente.'],
			["In today's competitive landscape,", 'No cenário competitivo atual,'],
			['data-driven decisions', 'decisões fundamentadas em dados'],
			['are no longer a differentiator', 'deixaram de ser diferencial'],
			['and have become essential', 'e tornaram-se essenciais'],
			['for success.', 'para o sucesso.'],
		],
	},
]
