export const typingData = [
	[
		["When you're on the highway,", 'Quando você está na rodovia,'],
		['use cruise control,', 'use o piloto automático,'],
		['which helps maintain', 'que ajuda a manter'],
		['a constant speed.', 'uma velocidade constante.'],
		['Use the highest gear possible', 'Use a marcha mais alta possível'],
		['and overdrive gears', 'e as marchas overdrive'],
		['if you have them.', 'se você as tiver.'],
		['The faster an engine is turning,', 'Quanto mais rápido o motor gira,'],
		["the more gas you're using.", 'mais gasolina você gasta.'],
		['Pay attention to', 'Preste atenção ao'],
		['your tachometer.', 'seu tacômetro.'],
		['Plus,', 'Além disso,'],
		['a slower turning engine', 'um motor que gira mais devagar'],
		['means less friction', 'significa menos atrito'],
		['and engine wear.', 'e menos desgaste do motor.'],
		['Avoid excessive idling.', 'Evite a marcha lenta excessiva.'],
	],
	[
		['Embedded systems', 'Os sistemas embarcados'],
		['play a fundamental role', 'têm papel fundamental'],
		['in the development of', 'no desenvolvimento de'],
		['Internet of Things (IoT) solutions,', 'soluções de Internet das Coisas (IoT),'],
		['with platforms like the ESP32 standing out.', 'destacando-se plataformas como o ESP32.'],
		['This microcontroller combines', 'Esse microcontrolador combina'],
		['low cost,', 'baixo custo,'],
		['low power consumption', 'baixo consumo de energia'],
		['and high processing capacity,', 'e alta capacidade de processamento,'],
		['while also offering', 'além de oferecer'],
		[
			'integrated Wi-Fi and Bluetooth Low Energy (BLE) connectivity.',
			'conectividade Wi-Fi e Bluetooth Low Energy (BLE) integradas.',
		],
		['Wi-Fi enables direct communication', 'O Wi-Fi permite comunicação direta'],
		['with servers,', 'com servidores,'],
		['cloud applications', 'aplicações em nuvem'],
		['and local networks,', 'e redes locais,'],
		['while BLE makes possible', 'enquanto o BLE possibilita'],
		['efficient connections', 'conexões eficientes'],
		['with smartphones, sensors', 'com smartphones, sensores'],
		['and low-power devices.', 'e dispositivos de baixo consumo energético.'],
		['This versatility makes the ESP32 ideal', 'Essa versatilidade torna o ESP32 ideal'],
		['for home automation,', 'para automação residencial,'],
		['industrial monitoring,', 'monitoramento industrial,'],
		['asset tracking', 'rastreamento de ativos'],
		['and smart projects in general,', 'e projetos inteligentes em geral,'],
		['accelerating the development', 'acelerando o desenvolvimento'],
		['of connected and scalable applications.', 'de aplicações conectadas e escaláveis.'],
	],
]
