export interface TypingData {
	id: string
	title: string
	data: string[][]
}

export const typingData: TypingData[] = [
	{
		id: '019ee625-b455-7c9f-9a17-a23a31310d05',
		title: 'Sensores MEMS na Manutenção Preditiva',
		data: [
			['MEMS sensors,', 'Os sensores MEMS,'],
			['especially accelerometers', 'especialmente acelerômetros'],
			['and inertial measurement units (IMU),', 'e unidades de medição inercial (IMU),'],
			['have transformed the way', 'têm transformado a forma como'],
			['industry monitors rotating equipment.', 'a indústria monitora equipamentos rotativos.'],
			['Installed in motors, pumps and gearboxes,', 'Instalados em motores, bombas e redutores,'],
			['these sensors capture', 'esses sensores capturam'],
			['vibration data in real time,', 'dados de vibração em tempo real,'],
			['allowing the identification of', 'permitindo identificar'],
			['abnormal patterns associated with', 'padrões anormais associados a'],
			['misalignments, imbalances,', 'desalinhamentos, desbalanceamentos,'],
			['bearing wear', 'desgaste de rolamentos'],
			['and other mechanical failures.', 'e outras falhas mecânicas.'],
			['Combined with IoT platforms', 'Combinados a plataformas IoT'],
			['and data analysis algorithms,', 'e algoritmos de análise de dados,'],
			['MEMS sensors enable', 'os sensores MEMS possibilitam'],
			['predictive maintenance,', 'a manutenção preditiva,'],
			['reducing unplanned downtime', 'reduzindo paradas não planejadas'],
			['and operational costs.', 'e custos operacionais.'],
			['Their compact size,', 'Seu tamanho compacto,'],
			['low power consumption', 'baixo consumo de energia'],
			['and affordable cost', 'e custo acessível'],
			['make this technology', 'tornam essa tecnologia'],
			['an increasingly adopted solution', 'uma solução cada vez mais adotada'],
			['in modern industry.', 'na indústria moderna.'],
		],
	},
	{
		id: '019ee625-ef84-79b5-a439-0ad6b911aa18',
		title: 'ESP32: Conectividade Inteligente para IoT',
		data: [
			['Embedded systems', 'Os sistemas embarcados'],
			['play a fundamental role', 'têm papel fundamental'],
			['in the development of', 'no desenvolvimento de'],
			['Internet of Things solutions,', 'soluções de Internet das Coisas,'],
			['with platforms like the ESP32 standing out.', 'destacando-se plataformas como o ESP32.'],
			['This microcontroller combines', 'Esse microcontrolador combina'],
			['low cost,', 'baixo custo,'],
			['low power consumption', 'baixo consumo de energia'],
			['and high processing capacity,', 'e alta capacidade de processamento,'],
			['while also offering', 'além de oferecer'],
			[
				'integrated WiFi and Bluetooth Low Energy connectivity.',
				'conectividade WiFi e Bluetooth Low Energy integradas.',
			],
			['WiFi enables direct communication', 'O WiFi permite comunicação direta'],
			['with servers,', 'com servidores,'],
			['cloud applications', 'aplicações em nuvem'],
			['and local networks,', 'e redes locais,'],
			['while BLE makes possible', 'enquanto o BLE possibilita'],
			['efficient connections', 'conexões eficientes'],
			['with smartphones, sensors', 'com smartphones, sensores'],
			['and low-power devices.', 'e dispositivos de baixo consumo energético.'],
			['This versatility makes the ESP32 ideal', 'Essa versatilidade torna o ESP32 ideal'],
			['for home automation,', 'para automação residencial,'],
			['industrial monitoring,', 'monitoramento industrial,'],
			['asset tracking', 'rastreamento de ativos'],
			['and smart projects in general,', 'e projetos inteligentes em geral,'],
			['accelerating the development', 'acelerando o desenvolvimento'],
			['of connected and scalable applications.', 'de aplicações conectadas e escaláveis.'],
		],
	},
	{
		id: '019ee665-fb5a-7dad-bf60-78a76574104b',
		title: 'Indústria 4.0 e a Transformação Digital',
		data: [
			['Industry 4.0 represents', 'A Indústria 4.0 representa'],
			['the integration of digital technologies', 'a integração de tecnologias digitais'],
			['into production processes,', 'aos processos produtivos,'],
			['making factories smarter,', 'tornando fábricas mais inteligentes,'],
			['more connected and efficient.', 'conectadas e eficientes.'],
			['In this scenario,', 'Nesse cenário,'],
			['IoT (Internet of Things) systems', 'os sistemas IoT (Internet das Coisas)'],
			['play a fundamental role', 'desempenham papel fundamental'],
			['in collecting real-time data', 'ao coletar dados em tempo real'],
			['from machines, sensors and equipment,', 'de máquinas, sensores e equipamentos,'],
			['enabling continuous monitoring', 'permitindo monitoramento contínuo'],
			['and decision-making', 'e tomada de decisões'],
			['based on accurate information.', 'baseada em informações precisas.'],
			['With the adoption of these technologies,', 'Com a adoção dessas tecnologias,'],
			[
				'industries are able to increase productivity,',
				'as indústrias conseguem aumentar a produtividade,',
			],
			['reduce waste,', 'reduzir desperdícios,'],
			['optimize energy consumption', 'otimizar o consumo de energia'],
			['and minimize unplanned downtime', 'e minimizar paradas não planejadas'],
			['through predictive maintenance.', 'por meio da manutenção preditiva.'],
			['In addition,', 'Além disso,'],
			['connectivity between systems', 'a conectividade entre sistemas'],
			['improves product quality', 'melhora a qualidade dos produtos'],
			['and competitiveness,', 'e a competitividade,'],
			['generating significant', 'gerando ganhos'],
			['operational and financial gains.', 'operacionais e financeiros significativos.'],
		],
	},
	{
		id: '019ee666-88a4-78f4-8fa6-78105ebe7bf5',
		title: 'BLE 5+: Mais Alcance e Velocidade com Energia Mínima',
		data: [
			['Bluetooth Low Energy technology', 'A tecnologia Bluetooth Low Energy'],
			['represents a milestone', 'representa um marco'],
			['in wireless communication', 'na comunicação sem fio'],
			['aimed at devices', 'voltada para dispositivos'],
			['that require energy efficiency.', 'que exigem eficiência energética.'],
			['With the arrival of version 5', 'Com a chegada da versão 5'],
			['and its later updates,', 'e suas atualizações posteriores,'],
			['BLE has evolved significantly:', 'o BLE evoluiu significativamente:'],
			['it doubled the transmission speed,', 'dobrou a velocidade de transmissão,'],
			['quadrupled the range', 'quadruplicou o alcance'],
			['and expanded the broadcast capacity,', 'e ampliou a capacidade de broadcast,'],
			['becoming ideal for IoT,', 'tornando-se ideal para IoT,'],
			['wearables and sensors.', 'vestíveis e sensores.'],
			['Its main differentiator', 'Seu principal diferencial'],
			['remains the extremely low', 'continua sendo o baixíssimo'],
			['power consumption,', 'consumo de energia,'],
			['allowing devices to operate', 'permitindo que dispositivos funcionem'],
			['for months or even years', 'por meses ou até anos'],
			['on a single coin cell battery.', 'com uma única bateria de moeda.'],
			['This combination', 'Essa combinação'],
			['of performance and economy', 'de desempenho e economia'],
			['established BLE as an essential standard', 'consolidou o BLE como padrão essencial'],
			['in modern connectivity.', 'na conectividade moderna.'],
		],
	},
]
